version: "3.3"
services:
  orders_ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=orders_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_PORT=5432
    ports:
      - 8080:8080
    depends_on:
      - orders_db

  orders_db:
    container_name: orders_db
    image: public.ecr.aws/bitnami/postgresql:14.3.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./etc/docker/init-db:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432